server:
  port: 8080
  read_timeout: "5s"
  write_timeout: "10s"
  idle_timeout: "10s"

database:
  host: localhost
  port: 5432
  user: postgres
  password: ""
  name: golos
  ssl_mode: disable

logger:
  level: "debug"
  json: false

migrations: 
  dir: "migrations/postgres"